import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Image from 'next/image';

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased bg-[#0C0C0C] font-sans`}
      >
        <div className='fixed inset-0 -z-10 overflow-hidden pointer-events-none'>
          <Image
            src='/Wave.svg'
            alt='bg-wave'
            fill
            className='object-cover'
            priority
          />
        </div>
        {children}
      </body>
    </html>
  );
}